issuer: https://token.actions.githubusercontent.com
subject: repo:chainguard-dev/mattmoor-actions:ref:refs/heads/main
claim_pattern:
  workflow_ref: chainguard-dev/mattmoor-actions/.github/workflows/octo-sts.yaml@refs/heads/main

permissions:
  contents: read
